services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017  # MongoDB connection
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    image: node:18-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

  mongodb:
    image: mongo:7.0
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all

