services:
  - type: web
    name: backend
    env: docker
    buildCommand: docker build -t backend -f backend/Dockerfile .
    startCommand: uvicorn main:app --host 0.0.0.0
    envVars:
      - key: MONGODB_URI
        value: mongodb://mongodb:27017
    dockerContext: .
    dockerfilePath: backend/Dockerfile

  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm run dev -- --host 0.0.0.0
    envVars:
      - key: PORT
        value: 5173

  - type: pserv
    name: mongodb
    env: docker
    image: mongo:7.0
    disk:
      name: mongodb_data
      mountPath: /data/db
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root
      - key: MONGO_INITDB_ROOT_PASSWORD
        generateValue: true
