services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    disk:
      name: backend-data
      mountPath: /app/backend
    envVars:
      - key: MONGODB_URI
        fromService:
          type: pserv
          name: mongodb
          envVarKey: MONGODB_URL
    healthCheckPath: /
    numInstances: 1
    region: oregon
    plan: starter

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    disk:
      name: frontend-data
      mountPath: /app/frontend
    healthCheckPath: /
    numInstances: 1
    region: oregon
    plan: starter

  - type: pserv
    name: mongodb
    env: docker
    dockerfilePath: ./Dockerfile.mongodb
    disk:
      name: mongodb-data
      mountPath: /data/db
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        generateValue: true
      - key: MONGO_INITDB_ROOT_PASSWORD
        generateValue: true
      - key: MONGODB_URL
        value: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
    region: oregon
    plan: starter
